export const clientData = [
  {
    id: 1,
    name: "TATA PROJECTS LTD.",
    logo: "/logos/Tata Projects Limited.webp",
    description: "Infrastructure and construction solutions.",
  },
  {
    id: 2,
    name: "RKCPL",
    logo: "/logos/rkcpl.webp",
    description: "Construction and infrastructure development.",
  },
  {
    id: 3,
    name: "KCPL",
    logo: "/logos/kcpl.webp",
    description: "Engineering and construction solutions.",
  },
  {
    id: 4,
    name: "M/S D. R. A. INFRACON PVT. LTD",
    logo: "/logos/dra.webp",
    description: "Infrastructure and civil construction.",
  },
  {
    id: 5,
    name: "SHIVALIYA CONSTRUCTION PVT. LTD",
    logo: "/logos/Shivaliya.webp",
    description: "Construction and development company.",
  },
  {
    id: 6,
    name: "KCC BUILDCON PVT. LTD",
    logo: "/logos/kcc.webp",
    description: "Building and construction solutions.",
  },
  {
    id: 7,
    name: "SP SINGLA CONSTRUCTION PVT. LTD",
    logo: "/logos/spsingla.webp",
    description: "Civil and infrastructure construction.",
  },
  {
    id: 8,
    name: "CHETAK ENTERPRISES LTD",
    logo: "/logos/chetak.webp",
    description: "Construction and infrastructure services.",
  },
  {
    id: 9,
    name: "REGAL ENTERPRISES",
    logo: "/logos/regal.webp",
    description: "Construction and engineering solutions.",
  },
  {
    id: 10,
    name: "PS CONSTRUCTION COMPANY",
    logo: "/logos/psconstruction.webp",
    description: "Construction and project development.",
  },
  {
    id: 11,
    name: "A.M. INFRACON",
    logo: "/logos/aminfra.webp",
    description: "Infrastructure and civil works.",
  },
  {
    id: 12,
    name: "S.S CHAUHAN CONST. PVT. LTD",
    logo: "/logos/ss.webp",
    description: "Construction and infrastructure projects.",
  },
  {
    id: 13,
    name: "S.S. INFRA",
    logo: "/logos/ssinfra.webp",
    description: "Infrastructure development solutions.",
  },
  {
    id: 14,
    name: "NEELKANTH RMC, ROHTAK",
    logo: "/logos/neelkanth.webp",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 15,
    name: "RAMA RMC, MIRTHAL",
    logo: "/logos/rmc.webp",
    description: "Ready-mix concrete and construction solutions.",
  },
  {
    id: 16,
    name: "SKYDREAM RMC, ROHTAK",
    logo: "/logos/skydream.webp",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 17,
    name: "ROYAL RESIDENCY, ZIRAKPUR",
    logo: "/logos/royal.webp",
    description: "Residential construction project.",
  },
  {
    id: 18,
    name: "SAHAJ INFRA",
    logo: "/logos/sahaj.webp",
    description: "Infrastructure and construction services.",
  },
  {
    id: 19,
    name: "BHARAT CONSTRUCTION COMPANY",
    logo: "/logos/bharat.webp",
    description: "Construction and infrastructure projects.",
  },
  {
    id: 20,
    name: "EMIRATE RESIDENCY, MOHALI",
    logo: "/logos/emirate.webp",
    description: "Residential construction project.",
  },
  {
    id: 21,
    name: "MORBAGH RESIDENCY, ROHTAK",
    logo: "/logos/morbagh.webp",
    description: "Residential development project.",
  },
  {
    id: 22,
    name: "RUDRA ENTERPRISES",
    logo: "/logos/rudra.webp",
    description: "Construction and engineering services.",
  },
  {
    id: 23,
    name: "RDS INFRA",
    logo: "/logos/rds.webp",
    description: "Infrastructure development company.",
  },
  {
    id: 24,
    name: "KM BUILDCON",
    logo: "/logos/kmbuildcon.webp",
    description: "Building and construction solutions.",
  },
  {
    id: 25,
    name: "RK INFRACON",
    logo: "/logos/rkinfra.webp",
    description: "Infrastructure and civil construction.",
  },
  {
    id: 26,
    name: "KMS BUILDCON PVT. LTD",
    logo: "/logos/kms.webp",
    description: "Building and construction projects.",
  },
  {
    id: 27,
    name: "SAR BUILDCON PVT. LTD",
    logo: "/logos/sar.webp",
    description: "Construction and development solutions.",
  },
  {
    id: 28,
    name: "CRP BUILDCON PVT. LTD",
    logo: "/logos/crp.webp",
    description: "Building and infrastructure development.",
  },
  {
    id: 29,
    name: "SHREE BALAJI BUILDWELL PVT. LTD",
    logo: "/logos/shreebalaji.webp",
    description: "Construction and real estate development.",
  },
  {
    id: 30,
    name: "PSY INFRASTRUCTURE PVT. LTD",
    logo: "/logos/psy.webp",
    description: "Infrastructure and construction projects.",
  },
  {
    id: 31,
    name: "SUSHMA RESIDENCY, ZIRAKPUR",
    logo: "/logos/sushma.webp",
    description: "Residential construction project.",
  },
  {
    id: 32,
    name: "ECO RESIDENCY, MOHALI",
    logo: "/logos/eco.webp",
    description: "Residential development project.",
  },
  {
    id: 33,
    name: "JYANTI CONSTRUCTION COMPANY",
    logo: "/logos/jyanti.webp",
    description: "Construction and infrastructure solutions.",
  },
  {
    id: 34,
    name: "BALAJI RMC, ROHTAK",
    logo: "/logos/balajirmc.webp",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 35,
    name: "BAJRANGBALI RMC, ROHTAK",
    logo: "/logos/bajrangbali.webp",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 36,
    name: "AND MANY MORE",
    logo: "/logos/andmanymore.webp",
    description: "And many more trusted clients.",
  },
];
