export const clientData = [
  {
    id: 1,
    name: "TATA PROJECTS LTD.",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=TATA+PROJECTS",
    description: "Infrastructure and construction solutions.",
  },
  {
    id: 2,
    name: "RKCPL",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=RKCPL",
    description: "Construction and infrastructure development.",
  },
  {
    id: 3,
    name: "KCPL",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=KCPL",
    description: "Engineering and construction solutions.",
  },
  {
    id: 4,
    name: "M/S D. R. A. INFRACON PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=D.R.A.+INFRACON",
    description: "Infrastructure and civil construction.",
  },
  {
    id: 5,
    name: "SHIVALIYA CONSTRUCTION PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SHIVALIYA",
    description: "Construction and development company.",
  },
  {
    id: 6,
    name: "KCC BUILDCON PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=KCC+BUILDCON",
    description: "Building and construction solutions.",
  },
  {
    id: 7,
    name: "SP SINGLA CONSTRUCTION PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SP+SINGLA",
    description: "Civil and infrastructure construction.",
  },
  {
    id: 8,
    name: "CHETAK ENTERPRISES LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=CHETAK",
    description: "Construction and infrastructure services.",
  },
  {
    id: 9,
    name: "REGAL ENTERPRISES",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=REGAL+ENTERPRISES",
    description: "Construction and engineering solutions.",
  },
  {
    id: 10,
    name: "PS CONSTUCTION COMPANY",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=PS+CONSTRUCTION",
    description: "Construction and project development.",
  },
  {
    id: 11,
    name: "A.M. INFRACON",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=AM+INFRACON",
    description: "Infrastructure and civil works.",
  },
  {
    id: 12,
    name: "S.S CHAUHAN CONST. PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SS+CHAUHAN",
    description: "Construction and infrastructure projects.",
  },
  {
    id: 13,
    name: "S.S. INFRA",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SS+INFRA",
    description: "Infrastructure development solutions.",
  },
  {
    id: 14,
    name: "NEELKANTH RMC, ROHTAK",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=NEELKANTH+RMC",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 15,
    name: "RAMA RMC, MIRTHAL",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=RAMA+RMC",
    description: "Ready-mix concrete and construction solutions.",
  },
  {
    id: 16,
    name: "SKYDREAM RMC, ROHTAK",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SKYDREAM+RMC",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 17,
    name: "ROYAL RESIDENCY, ZIRAKPUR",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=ROYAL+RESIDENCY",
    description: "Residential construction project.",
  },
  {
    id: 18,
    name: "SAHAJ INFRA",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SAHAJ+INFRA",
    description: "Infrastructure and construction services.",
  },
  {
    id: 19,
    name: "BHARAT CONSTRUCTION COMPANY",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=BHARAT+CONSTRUCTION",
    description: "Construction and infrastructure projects.",
  },
  {
    id: 20,
    name: "EMIRATE RESIDENCY, MOHALI",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=EMIRATE+RESIDENCY",
    description: "Residential construction project.",
  },
  {
    id: 21,
    name: "MORBAGH RESIDENCY, ROHTAK",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=MORBAGH+RESIDENCY",
    description: "Residential development project.",
  },
  {
    id: 22,
    name: "RUDRA ENTERPRISES",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=RUDRA+ENTERPRISES",
    description: "Construction and engineering services.",
  },
  {
    id: 23,
    name: "RDS INFRA",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=RDS+INFRA",
    description: "Infrastructure development company.",
  },
  {
    id: 24,
    name: "KM BUILDCON",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=KM+BUILDCON",
    description: "Building and construction solutions.",
  },
  {
    id: 25,
    name: "RK INFRACON",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=RK+INFRACON",
    description: "Infrastructure and civil construction.",
  },
  {
    id: 26,
    name: "KMS BUILDCON PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=KMS+BUILDCON",
    description: "Building and construction projects.",
  },
  {
    id: 27,
    name: "SAR BUILDCON PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SAR+BUILDCON",
    description: "Construction and development solutions.",
  },
  {
    id: 28,
    name: "CRP BUILDCON PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=CRP+BUILDCON",
    description: "Building and infrastructure development.",
  },
  {
    id: 29,
    name: "SHREE BALAJI BUILDWELL PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SHREE+BALAJI",
    description: "Construction and real estate development.",
  },
  {
    id: 30,
    name: "PSY INFRASTRUCTURE PVT. LTD",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=PSY+INFRASTRUCTURE",
    description: "Infrastructure and construction projects.",
  },
  {
    id: 31,
    name: "SUSHMA RESIDENCY, ZIRAKPUR",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=SUSHMA+RESIDENCY",
    description: "Residential construction project.",
  },
  {
    id: 32,
    name: "ECO RESIDENCY, MOHALI",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=ECO+RESIDENCY",
    description: "Residential development project.",
  },
  {
    id: 33,
    name: "JYANTI CONSTRUCTION COMPANY",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=JYANTI+CONSTRUCTION",
    description: "Construction and infrastructure solutions.",
  },
  {
    id: 34,
    name: "BALAJI RMC, ROHTAK",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=BALAJI+RMC",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 35,
    name: "BAJRANGBALI RMC, ROHTAK",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=BAJRANGBALI+RMC",
    description: "Ready-mix concrete solutions.",
  },
  {
    id: 36,
    name: "AND MANY MORE",
    logo: "https://placehold.co/500x220/ffffff/0f172a?text=AND+MANY+MORE",
    description: "And many more trusted clients.",
  },
];